name: Build MaplePSA
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Surgical Patch (Fixing Dev's Shitcode)
      shell: powershell
      run: |
        $code = Get-Content -Raw MaplePS.cpp
        # Меняем хардкод ANSI-функций на Wide-версии
        $code = $code.Replace('CreateProcessA', 'CreateProcessW')
        $code = $code.Replace('GetFileAttributesA', 'GetFileAttributesW')
        $code = $code.Replace('SetFileAttributesA', 'SetFileAttributesW')
        $code = $code.Replace('DeleteFileA', 'DeleteFileW')
        $code = $code.Replace('CopyFileA', 'CopyFileW')
        $code = $code.Replace('lstrcmpA', 'lstrcmpW')
        
        # Вырезаем нахуй кривой wcstombs_s со всеми аргументами до точки с запятой
        $code = $code -replace 'wcstombs_s[^;]+;', ''
        
        $code | Set-Content MaplePS.cpp

    - name: Build Solution
      run: msbuild MaplePS.sln /p:Configuration=Release /p:Platform=x64 /p:CharacterSet=Unicode

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MaplePS-Binary
        path: x64/Release/
