name: Build MaplePSA
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild MaplePS.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MaplePS-Binary
        path: x64/Release/ # Чекай, если билд упадет, возможно путь другой (например просто Release/)
